### ISSUE TITLE
Fix before workshop

### ISSUE THREAD

**Issue by jl-wynen** [SciCatProject/scicat-workshop#1]
- [x] why is the file called `environment/pip-scicat-workshopwq.txt`? Esp. the `wq` suffix. Need to update `SETUP.md` if this is intentional.
- [x] The exercise notebook is called `exercise_6` but the solution is `exercise_1`. Intentional? 
- [x] I can't find `scicat-wortshop.html`
- [x] Remove `.ipynb_checkpoints` in `images`
- [x] I can't find `scicat-workshop-solutions.ipynb` and `scicat-workshop-solutions.html`
- [x] Names of exercise files in README

**Comment by nitrosx** [comment]
`environment/pip-scicat-workshopwq.txt` is an error. It should be `environment/pip-scicat-workshop.txt`

**Comment by nitrosx** [comment]
Solution for `exercise_6` should be called `exercise_6_with_solution.ipynb`
